---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    physical:
      hosts:
        anton:
          ansible_host: 192.168.0.5
        nuc:
          ansible_host: 192.168.0.6
        storinator:
          ansible_host: 192.168.0.4
        orangepi:
          ansible_host: 192.168.0.7
          ansible_user: root  # Orange Pi default

    nuc_vms:
      vars:
        proxmox_node: nuc
      hosts:
        nuc-infisical:
          ansible_host: 192.168.0.21

    anton_vms:
      vars:
        proxmox_node: anton
      hosts:
        # Populated as VMs are added

    vms:
      children:
        nuc_vms:
        anton_vms:
