global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: node
    static_configs:
      - targets:
          - diglett-infra:9100
          - alakazam-deploy:9100
          - diglett-dns:9100
          - machamp-media:9100
          - machamp-dev:9100
          - machamp-monitor:9100

  - job_name: traefik
    static_configs:
      - targets: [diglett-infra:8082]

  - job_name: jellyfin
    static_configs:
      - targets: [machamp-media:8096]
    metrics_path: /metrics
