---
- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true

- name: Restart tailscale
  ansible.builtin.service:
    name: tailscaled
    state: restarted
  become: true

- name: Restart avahi-daemon
  ansible.builtin.service:
    name: avahi-daemon
    state: restarted
  become: true
  failed_when: false
