---
- name: Configure VMs with vm_role
  hosts: vms
  become: true
  roles:
    - base
  tasks:
    - name: Check if vm_role role directory exists
      stat:
        path: "{{ playbook_dir }}/roles/{{ vm_role }}"
      register: role_dir
      when: vm_role is defined
      delegate_to: localhost

    - name: Apply vm_role
      include_role:
        name: "{{ vm_role }}"
      when: vm_role is defined and role_dir.stat.exists
