---
- name: Restart dns stack
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/homelab/services/dns
    state: restarted
  become: true

- name: Restart headplane
  community.docker.docker_container:
    name: headplane
    state: started
    restart: true
  become: true

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  become: true
